@startuml
start
if (CurrentCheck.isEmpty()) then (true)
:Terminal.applyCurrentCheck();
:Terminal.printCurrentCheck();
:Terminal.showChange();
:Terminal.openMoneyCase();
:Terminal.waitForCaseClosing();
else(false)
endif
stop
@enduml
